version: '3.1'

services:
  client-certificates:
    image: barumel/nginx-client-certificates:latest
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - "CERTIFICATES_SERVER_CERTIFY_DAYS=${CERTIFICATES_SERVER_CERTIFY_DAYS}"
      - "CERTIFICATES_SERVER_PASSPHRASE=${CERTIFICATES_SERVER_PASSPHRASE}"
      - "CERTIFICATES_SERVER_COUNTRY=${CERTIFICATES_SERVER_COUNTRY}"
      - "CERTIFICATES_SERVER_STATE=${CERTIFICATES_SERVER_STATE}"
      - "CERTIFICATES_SERVER_LOCALITY=${CERTIFICATES_SERVER_LOCALITY}"
      - "CERTIFICATES_SERVER_ORGANIZATION=${CERTIFICATES_SERVER_ORGANIZATION}"
      - "CERTIFICATES_SERVER_ORGANIZATIONAL_UNIT=${CERTIFICATES_SERVER_ORGANIZATIONAL_UNIT}"
      - "CERTIFICATES_SERVER_COMMON_NAME=${CERTIFICATES_SERVER_COMMON_NAME}"
    volumes:
     - certificates:/srv/certificates

volumes:
  certificates:
