version: '3.1'

services:
  client-certificates:
    image: barumel/nginx-client-certificates:latest
    environment:
      - "PASSPHRASE=MySuperSecurePassphrase"
      - "COUNTRY=CH"
      - "STATE=Neuchatel"
      - "LOCALITY=La Sagne"
      - "ORGANIZATION=Example Org"
      - "ORGANIZATIONAL_UNIT=Example Unit"
      - "COMMON_NAME=example.ch"
      - "SSL_CLIENT_CERTIFICATES_FOR=foo,bar"
      - "SSL_CLIENT_PASSPHRASE=MySuperSecureClientPassphrase"
    volumes:
     - ca:/etc/ssl/ca
     - ./certificates:/etc/ssl/ca/export
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ca:/etc/ssl/ca
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./files/custom.conf:/etc/nginx/conf.d/my_proxy.conf:ro
      - ./files/openssl.cnf:/etc/ssl/openssl.cnf

volumes:
  ca:
